services:
  - name: x-to-bsky-bot
    image: python:3.9-slim-buster  # Or a suitable Python image
    ports:
      - 8000:8000  # Map container port 8000 to Koyeb port 8000
    build:
      type: python
      build_command: pip install -r requirements.txt
    run:
      command: python main.py
    env:
      - BSKY_HANDLE=${BSKY_HANDLE}
      - BSKY_APP_PASSWORD=${BSKY_APP_PASSWORD}
    routes:
      - src: /
        dest: /
